-- =============================================================================
-- Migration: 001_auth_foundation.sql
-- Phase:     1 - Authentication Database & Configuration Foundation
-- Purpose:   Extend USERS with auth/2FA bookkeeping columns and add a
--            dedicated AUTH_AUDIT_LOG table for authentication events.
--
-- SAFETY NOTES (read before running):
--   - This migration only ALTERs the existing USERS table in place. It does
--     NOT drop, recreate, or rename USERS, and does not touch any existing
--     USERS columns, constraints, or rows.
--   - This migration does NOT modify the generic AUDIT_LOG table.
--   - This migration does NOT touch PRODUCTS, SALES, INVENTORY, CATEGORIES,
--     UNITS, or any other business table.
--   - This migration does NOT insert any rows (no seed/demo/test users).
--   - Run each statement inside a transaction-aware tool (e.g. SQL*Plus,
--     SQLcl) that will stop on the first error (WHENEVER SQLERROR EXIT).
--   - This migration is idempotent-by-guard only (see checks below), not
--     idempotent-by-design: re-running it after a partial failure requires
--     manually checking which statements already succeeded before re-running
--     the remainder. Do not blindly re-run the whole file if it already
--     partially applied.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- PRE-FLIGHT (run manually and review before applying anything below):
--
--   -- Confirm USERS exists and inspect its current columns:
--   SELECT column_name, data_type, nullable FROM user_tab_columns
--   WHERE table_name = 'USERS' ORDER BY column_id;
--
--   -- Confirm this migration has not already been applied:
--   SELECT column_name FROM user_tab_columns
--   WHERE table_name = 'USERS'
--     AND column_name IN ('FAILED_LOGIN_COUNT','LOCKOUT_END_AT',
--                          'TWO_FACTOR_ENABLED','TWO_FACTOR_SECRET','UPDATED_AT');
--   SELECT table_name FROM user_tables WHERE table_name = 'AUTH_AUDIT_LOG';
--
--   If either query returns rows, STOP. Do not run this file — report back
--   instead, since re-running would raise ORA-01430 / ORA-00955 or silently
--   duplicate objects.
-- -----------------------------------------------------------------------------

WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- -----------------------------------------------------------------------------
-- 1. Extend USERS (additive only; existing columns/constraints untouched)
-- -----------------------------------------------------------------------------

ALTER TABLE USERS ADD (
  FAILED_LOGIN_COUNT  NUMBER(3)     DEFAULT 0 NOT NULL,
  LOCKOUT_END_AT      TIMESTAMP(6)  NULL,
  TWO_FACTOR_ENABLED  NUMBER(1)     DEFAULT 0 NOT NULL,
  TWO_FACTOR_SECRET   VARCHAR2(255) NULL,
  UPDATED_AT          TIMESTAMP(6)  DEFAULT SYSTIMESTAMP
);

ALTER TABLE USERS ADD CONSTRAINT CK_USERS_FAILED_LOGIN_COUNT
  CHECK (FAILED_LOGIN_COUNT >= 0);

ALTER TABLE USERS ADD CONSTRAINT CK_USERS_TWO_FACTOR_ENABLED
  CHECK (TWO_FACTOR_ENABLED IN (0,1));

-- -----------------------------------------------------------------------------
-- 2. Create AUTH_AUDIT_LOG (new, separate from the existing generic AUDIT_LOG)
-- -----------------------------------------------------------------------------

CREATE TABLE AUTH_AUDIT_LOG (
  AUTH_LOG_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USER_ID              NUMBER NULL,
  USERNAME_ATTEMPTED   VARCHAR2(50) NULL,
  EVENT_TYPE           VARCHAR2(30) NOT NULL,
  EVENT_RESULT         VARCHAR2(10) NOT NULL,
  IP_ADDRESS           VARCHAR2(45) NULL,
  USER_AGENT           VARCHAR2(255) NULL,
  DETAIL               VARCHAR2(500) NULL,
  CREATED_AT           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_AUTH_AUDIT_LOG_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL,
  CONSTRAINT CK_AUTH_AUDIT_LOG_EVENT_TYPE
    CHECK (EVENT_TYPE IN (
      'REGISTER_SUCCESS','REGISTER_FAILURE',
      'LOGIN_SUCCESS','LOGIN_FAILURE','ACCOUNT_LOCKOUT',
      '2FA_SETUP','2FA_ENABLED','2FA_DISABLED',
      '2FA_VERIFY_SUCCESS','2FA_VERIFY_FAILURE'
    )),
  CONSTRAINT CK_AUTH_AUDIT_LOG_EVENT_RESULT
    CHECK (EVENT_RESULT IN ('SUCCESS','FAILURE'))
);

CREATE INDEX IX_AUTH_AUDIT_LOG_USER_ID ON AUTH_AUDIT_LOG(USER_ID);
CREATE INDEX IX_AUTH_AUDIT_LOG_CREATED_AT ON AUTH_AUDIT_LOG(CREATED_AT);

-- -----------------------------------------------------------------------------
-- End of migration 001_auth_foundation.sql
-- -----------------------------------------------------------------------------
